import type { Metadata } from 'next'
import '@/app/globals.css'
import { mainFont } from '@/components/fonts'
import { ClerkProvider, SignedIn, SignedOut } from '@clerk/nextjs'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={
            mainFont.className + ' h-screen flex items-center justify-center'
          }>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
