import type { Metadata } from 'next'
import '../globals.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import { mainFont } from '@/components/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        style={{
          padding: '0 2rem'
        }}
        className={mainFont.className + ' flex flex-col gap-4'}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
