import type { Metadata } from 'next'
import '../globals.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import { mainFont } from '@/components/fonts'
import { Toaster } from '@/components/ui/toaster'
import { ShoppingBagProvider } from '@/components/providers/shopping-bag-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ShoppingBagProvider>
        <body
          style={{
            padding: '0 1.75rem'
          }}
          className={mainFont.className + ' flex flex-col gap-4'}>
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </body>
      </ShoppingBagProvider>
    </html>
  )
}
