import type { Metadata } from 'next'
import '@uploadthing/react/styles.css'
import '../globals.css'
import Navbar from './_components/navbar'
import Providers from '@/components/providers'
import { mainFont } from '@/components/fonts'
import BreadcrumbWrapper from '@/components/ui/breadcrumb-wrapper'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={
            mainFont.className + ' grid grid-rows-[80px_1fr] h-screen'
          }>
          <Navbar />
          <main className="bg-zinc-50 dark:bg-background h-full flex flex-col gap-4 p-6">
            <BreadcrumbWrapper isDashboard />
            {children}
          </main>
        </body>
      </Providers>
    </html>
  )
}
