import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Navbar from './_components/navbar'
import Title from './_components/title'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' flex gap-8'}>
        <Navbar />
        <main className="flex-1 py-6">
          <Title />
          {children}
        </main>
      </body>
    </html>
  )
}
