import type { Metadata } from 'next'
import '@uploadthing/react/styles.css'
import '../globals.css'
import Navbar from './_components/navbar'
import Providers from '@/components/providers'
import { mainFont } from '@/components/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={mainFont.className + ' flex flex-col'}>
          <Navbar />
          <main className="bg-zinc-50 flex-1 flex flex-col gap-4 p-6">
            {children}
          </main>
        </body>
      </Providers>
    </html>
  )
}
